name: PR label

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  semver-label-check:
    name: Semantic version label check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check for Semantic Version label
        uses: apple/swift-nio/.github/actions/pull_request_semver_label_checker@feaf4ac57e27e411e83e88ee2f9b1789ddf08d0b
